@startuml

interface InstantiationStrategy {
    + instantiate(BeanDefinition beanDefinition) : Object
}

class SimpleInstantiationStrategy implements InstantiationStrategy {
    + instantiate(BeanDefinition beanDefinition) : Object
}

class CglibSubclassingInstantiationStrategy implements InstantiationStrategy {
    + instantiate(BeanDefinition beanDefinition) : Object
}

@enduml
